name: Build

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  win64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Install vcpkg
      uses: lukka/run-vcpkg@v6.2
      with:
        setupOnly: true
        vcpkgGitCommitId: a84190e1deca1b6a466a82b439e5e4b9f8c41b0e

    - name: Install Dependencies
      shell: cmd
      run: ".\\tools\\install-deps.bat"

    - name: Run CMake
      shell: powershell
      run: ".\\tools\\cmake.bat"

    - name: Build
      run: msbuild /m /p:Configuration=${{env.BUILD_TYPE}} build/NARC.sln
      
    - name: Upload Portable ZIP
      uses: actions/upload-artifact@v2
      with:
        name: NARC-win-x64-portable
        path: |
          build/Release/*
